### ISSUE TITLE
Feature: Write routes for user collection and setup user authentication

### ISSUE THREAD

**Issue by AlexDring** [AlexDring/spicy-orange-expressjs#9]
# Epic Title

Feature: Write routes for user collection and setup user authentication

## Epic Description

This Feature will setup routes to GET, POST, PUT and Delete documents in the _user_ collection

## List of Tasks (Complete in order)

1. [x] Setup user model #13 
2. [x] Write Jest tests #14 
3. [x] Setup user controller #16 

![image](https://user-images.githubusercontent.com/38809859/119955545-0da84d80-bf98-11eb-87fd-81d715d9a887.png)
